<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Promise</title>
</head>
<body>
    <script>
        function timeout(ms){
            return new Promise((resolve, reject) => {
                setTimeout(resolve, ms, 'done'); // 为啥可以传‘done'??????
            })
        }
        
        timeout(5000).then((value)=> {
            console.log(value);
        })

        // promise 新建后会立即执行
        let promise2 = new Promise(function(resolve, reject) {
            console.log('Promise');
            resolve(1);
        })

        promise2.then(function(val){
            console.log(val);
        })

        console.log('hello');


        // 异步加载图片
        function loadImageAsync(url){
            return new Promise(function(resolve, reject){
                const image = new Image();

                image.onload = function(){
                    resolve(image);
                }
                image.onerror = function(){
                    reject(new Error('could not load image'));
                }

                image.src = url;
            })
        }
        loadImageAsync('http://f11.baidu.com/it/u=3280610576,457503181&fm=72');


        // resolve函数和reject函数时带有参数，那么它们的参数会被传递给回调函数
        const p1 = new Promise(function(resolve, reject){
            setTimeout(()=> reject(new Error('fail')),3000)
        })
        const p2 = new Promise(function(resolve, reject){
            setTimeout(()=>resolve(p1),1000);
        })

        p2.then(result => console.log(result))
        .catch(error => console.log(error))


        // Promise.all() 用于将多个promise实例，包装成一个新的Promise实例
        /*
        const promises = [1,2,34,5,6,34].map(function(id){
            return getJSON('/post/'+id+".json");
        })

        Promise.all(promises).then(function(posts){
            //
        }).catch(function(reson){
            //...
        })
        */

        const p3 = new Promise((resolve, reject) => {
            resolve('hell');
        }).then(result => result)
        .catch(e=>e);

        const p4 = new Promise((resolve, reject) =>{
            resolve('world');
        })
        .then(result => result)
        .catch(e => e);

        Promise.all([p3,p4])
        .then(res => console.log(res))
        .catch(e => colsole.log(e));


        // Promise.race() 同样是将多个 Promise 实例，包装成一个新的 Promise 实例。
        const racePromise = Promise.race([p1,p2,p3]); //只要p1、p2、p3之中有一个实例率先改变状态，racePromise的状态就跟着改变
        // const racePromise2 = Promise.race([
        //     fetch('/resource-that-take-a-while'),
        //     new Promise(function(resolve, reject){
        //         setTimeout(function() {
        //             reject(new Error('request timeout'));
        //         }, 5000);
        //     })
        // ])
        // racePromise2.then(res => console.log(res))
        // racePromise2.catch(e => console.log(e));

        // Promise.resolve() 有时需要将现有对象转为 Promise 对象，Promise.resolve方法就起到这个作用
        let thenable = {
            then: function(resolve, reject){
                resolve(110) //立即执行thenable对象的then方法
            }
        }
        let p5 = Promise.resolve(thenable)
        .then(function(val){
            console.log(val);
        })

        // Promise.reject() Promise.reject(reason)方法也会返回一个新的 Promise 实例，该实例的状态为rejected
        // const p7 = Promise.reject('出错了');
        // 等同于
        // const p7 = new Promise((resolve, reject) => reject('出错了ttt'))

        // p7then(null, function (s) {
        //     console.log(s)
        // });
        // 出错了


        // 两个有用的方法  done() finally()
        // done() done方法，总是处于回调链的尾端，保证抛出任何可能出现的错误
        // finally方法用于指定不管 Promise 对象最后状态如何，都会执行的操作。它与done方法的最大区别，它接受一个普通的回调函数作为参数，该函数不管怎样都必须执行。


        // Generator函数与Promise的结合使用
        // 使用 Generator 函数管理流程，遇到异步操作的时候，通常返回一个Promise对象。
        function getFoo() {
            return new Promise(function(resolve, reject){
                resolve('foo');
            });
        }

        const g = function*(){
            try{
                const foo = yield getFoo();
                console.log(foo);
            } catch (e) {
                console.log(e);
            }
        }

        function run (generator) {
            const it = generator();

            function go(res) {
                if(res.done) return res.value;

                return res.value.then(function(value){
                    return go(it.next(value));
                },function(e){
                    return go(it.throw(e));
                })
            }

            go(it.next());
        }

        run(g);


        // Promise.try()
        // 不知道或者不想区分，函数f是同步函数还是异步操作，但是想用 Promise 来处理它。因为这样就可以不管f是否包含异步操作，都用then方法指定下一步流程，用catch方法处理f抛出的错误。一般就会采用下面的写法。
        // Promise.resolve.then(f)
        const f = () => console.log('now'); 
        Promise.resolve().then(f); //本轮事件循环的末尾执行
        console.log('next');

        // 让同步函数同步执行，异步函数异步执行，并且让它们具有统一的 API 呢
        const f2 = () => console.log('now2');
        (async () => f2())();
        console.log('next2');

        // try()
        const f3 = () => console.log('now3');
        Promise.try(f3);
        console.log('next3');


    </script>
    
</body>
</html>